/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.easykanban;
//importing the ImageIcon package to set and display icons
import javax.swing.ImageIcon;

/**
 *
 * @author ebenm
 */
public class RegistrationPage extends javax.swing.JFrame {
    private final ImageIcon imgIcon1 = new ImageIcon("Registration.png");
    /**
     * Creates new form RegistrationPage
     */
    public RegistrationPage() {
        initComponents(); 
        //position the JFrame in the center of the screen
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        registerButton.setFocusable(false);
        resetButton.setFocusable(false);
        iconLabel2.setText("");
        
        //displaying the icon on the frame
        iconLabel2.setIcon(imgIcon1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrationPanel = new javax.swing.JPanel();
        firstnameLabel = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        firstnameText = new javax.swing.JTextField();

        lastnameText = new javax.swing.JTextField();
        usernameText = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        iconPanel = new javax.swing.JPanel();
        iconLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyKanaban Registration");
        setBackground(new java.awt.Color(255, 255, 255));

        registrationPanel.setBackground(new java.awt.Color(165, 122, 255));
        registrationPanel.setMaximumSize(new java.awt.Dimension(627, 370));

        firstnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        firstnameLabel.setForeground(new java.awt.Color(0, 0, 0));
        firstnameLabel.setText("First name:");

        lastnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lastnameLabel.setForeground(new java.awt.Color(0, 0, 0));
        lastnameLabel.setText("Last name:");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        usernameLabel.setText("Username:");

        firstnameText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lastnameText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        usernameText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 0, 0));
        passwordLabel.setText("Password:");

        passwordText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        registerButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel1.setText("One more step to go!");
        jLabel1.setToolTipText("");

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginLabel.setText("Login to existing account");
        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseLabelClicked(evt);
            }
        });

        javax.swing.GroupLayout registrationPanelLayout = new javax.swing.GroupLayout(registrationPanel);
        registrationPanel.setLayout(registrationPanelLayout);
        registrationPanelLayout.setHorizontalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registrationPanelLayout.createSequentialGroup()
                                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstnameLabel)
                                    .addComponent(passwordLabel)
                                    .addComponent(usernameLabel)
                                    .addComponent(lastnameLabel))
                                .addGap(30, 30, 30)
                                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lastnameText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(registrationPanelLayout.createSequentialGroup()
                                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                        .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(93, 93, 93))))
        );
        registrationPanelLayout.setVerticalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLabel)
                    .addComponent(firstnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLabel)
                    .addComponent(lastnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(45, 45, 45)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        iconPanel.setBackground(new java.awt.Color(255, 255, 255));

        iconLabel2.setBackground(new java.awt.Color(255, 255, 255));
        iconLabel2.setForeground(new java.awt.Color(0, 0, 0));
        iconLabel2.setText("jLabel1");

        javax.swing.GroupLayout iconPanelLayout = new javax.swing.GroupLayout(iconPanel);
        iconPanel.setLayout(iconPanelLayout);
        iconPanelLayout.setHorizontalGroup(
            iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );
        iconPanelLayout.setVerticalGroup(
            iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(registrationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(registrationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    //creating a method to access the username from other classes or inside other methods
    public static String getUserName(){
        return usernameText.getText();
    }
    
    //creating a method to access the use's password from other classes or inside other methods
    public static String getPassword(){
        return String.valueOf(passwordText.getPassword());
    }
    
    //creating a method to access the user's first name from other classes or inside other methods
    public static String getFirstname(){
        return firstnameText.getText();
    }
    
    //creating a method to access the user's surname from other classes or inside other methods
    public static String getLastname(){
        return lastnameText.getText();
    }
    
    //creating a method to set the username from other classes or inside other methods
    public static void setUsername(String username){
        usernameText.setText(username);
    }
    
    //creating a method to set the user's password from other classes or inside other methods
    public static void setPassword(String password){
        passwordText.setText(password);
    }
    
    //Clearing the JTextFields and JPasswordFields when the reset button is clicked 
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == resetButton){
        firstnameText.setText("");
        lastnameText.setText("");
        usernameText.setText("");
        passwordText.setText("");
        }
    }//GEN-LAST:event_resetButtonActionPerformed
    
    /*validating whether or not the entered credentials are formatted correctly and whether or not the credentials already exists
    inside the text file, if the credentials don't exist and username and password complexity requirements are met,
    the user's account will be created, and they will be redirected to the login page
    if one or both conditions are not met, the user's account will not be created
    */
    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == registerButton){
        Login getMethodsObj = new Login(); 
            if(getMethodsObj.registerUser(getUserName(), getPassword()).equals("Password successfully captured")){
                     Login.writingToTextFile(getUserName(), getPassword(), getFirstname(), getLastname());
                         this.dispose();
                         java.awt.EventQueue.invokeLater(() -> {
                             new LoginPage().setVisible(true);
                     });
            }
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    //creating a new thread and displaying the login page when the label is clicked
    private void mouseLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseLabelClicked
        // TODO add your handling code here:
        if(evt.getSource() == loginLabel){
            this.dispose();
            java.awt.EventQueue.invokeLater(() -> {
                new LoginPage().setVisible(true);
            });
        }
    }//GEN-LAST:event_mouseLabelClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        //</editor-fold>
        
        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstnameLabel;
    protected static javax.swing.JTextField firstnameText;
    private javax.swing.JLabel iconLabel2;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastnameLabel;
    protected static javax.swing.JTextField lastnameText;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel passwordLabel;
    protected static javax.swing.JPasswordField passwordText;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registrationPanel;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel usernameLabel;
    protected static javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
